name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        # matrix allows you to run the multiple jobs simultaneously with different configurations
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
