name: Test project
on: push
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Change directory to second_action
        run: cd second_action
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
